# Generated by Django 3.2.9 on 2021-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userLogin', models.CharField(max_length=128)),
                ('userID', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
